### ISSUE TITLE
Absorbs are not being shown properly

### ISSUE THREAD

**Issue by Sammers21** [Sammers21/sArena_Updated2_by_sammers#8]
They are not being shown at all atm.

**Comment by devai42coding** [comment]
@Sammers21 Do you have an example of what it should show? Just to get an idea of what is not working and how it should be displayed when working

**Comment by Sammers21** [comment]
![image](https://github.com/user-attachments/assets/c2445898-19b0-4d82-ba41-28167c9c7d6e)
@devai42coding, this the the example of the absorb texture

**Comment by devai42coding** [comment]
Hi @Sammers21 

I have had a look at the API changes and it indeed look like they removed the used templates back then.

However, it looks like they have added the templates back on Beta.

These are the templates on live:

https://github.com/Gethe/wow-ui-source/blob/live/Interface/AddOns/Blizzard_UnitFrame/UnitFrame.xml

These are the templates on beta:

https://github.com/Gethe/wow-ui-source/blob/beta/Interface/AddOns/Blizzard_UnitFrame/UnitFrame.xml


This shows the templates that were used with sArena back then are readded back.

I have reverted the changes you did back then to solve the XML issues below:

https://github.com/devai42coding/sArena_Updated2_by_sammers/commit/a57ae0f3dc0578e43b2ffa8edfaea7455bac8d4f

I have not been able to test this yet at all, but I Think we should try to test this to see if it works again since the removed templates are back.

**Comment by devai42coding** [comment]
I just got to test it on Beta. Unfortunately I did not work - There are no lua errors, but it seems the functionality somewhere must have changed.

**Comment by devai42coding** [comment]
@Sammers21  - Created a PR for absorb implementation that have worked for me in the last 3 lobbies. Might still need some work, but it’s a start. PR also fixes other issues

**Comment by Sammers21** [comment]
It looks like the whole structure is too densed into a small thing
![image](https://github.com/user-attachments/assets/aea045bc-d69c-46ef-a6ca-e64c8da97d84)

It should look more like:
![image](https://github.com/user-attachments/assets/ee602dbe-74c7-41ad-870a-c08abf0d2d29)


@devai42coding here is the vod where i play with the new version https://www.twitch.tv/videos/2205909170

**Comment by devai42coding** [comment]
@Sammers21 You mean the texturepool is different on sarena and party frames? Yes unfortunately implementing the texture (two textures) actually that is implemented on the party frames was causing issues, so I went with the shield-fill texture just to get the absorb implementation in a working state.

**Comment by Sammers21** [comment]
@devai42coding is it possible to use the same texture as on party frames? Its been looking the same before it broke

**Comment by devai42coding** [comment]
@Sammers21 It is possible yes - Will take a bit to implement, but should be easier to test since new patch is live. I will give it a look when possible.

**Comment by Sammers21** [comment]
@devai42coding ait thank you. Would be nice

**Comment by devai42coding** [comment]
@Sammers21 Is this better?
![image](https://github.com/user-attachments/assets/a51e5f06-b426-49cf-801c-9596e220455f)
